### ISSUE TITLE
Request an example for using rollbar outside of components/pages (i.e. custom hook or util file)

### ISSUE THREAD

**Issue by partounian** [rollbar/rollbar-react#127]
Hello,

I'm a full stack / DevOps eng, and sadly my React / Next.js knowledge isn't the greatest. I've been having difficulty wrapping my head around how I can access Rollbar and it's provider from custom hook or util files. Would love to see an example

**Comment by zdavis-rollbar** [comment]
Hye @partounian,   You could use the pattern of the ReactSDK called `useRollbar`. https://github.com/rollbar/rollbar-react/blob/main/src/hooks/use-rollbar.js.

**Comment by zdavis-rollbar** [comment]
You could use our hook 'useRollbar' that you can find [here]( https://github.com/rollbar/rollbar-react/blob/main/src/hooks/use-rollbar.js)
