### ISSUE TITLE
ReferenceError: useEffect is not defined

### ISSUE THREAD

**Issue by sara-jegorova** [rollbar/rollbar-react#15]
When using `useRollbarContext` in a component, I get the error:
![Screenshot 2021-09-06 at 13 24 52](https://user-images.githubusercontent.com/86767207/132209016-27ff92b7-1b31-4701-a0dd-e04479ff7732.png).

It looks like neither `useEffect` or `useLayoutEffect` are being imported in https://github.com/rollbar/rollbar-react/blob/main/src/hooks/use-rollbar-context.js

Version: 0.8.0

**Comment by waltjones** [comment]
Fixed in v0.10.0. PR is here: https://github.com/rollbar/rollbar-react/pull/34
