### ISSUE TITLE
Next.js Examples

### ISSUE THREAD

**Issue by chrillep** [rollbar/rollbar-react#25]
like sentry could you please add examples of usage client and serverside for

- nextjs
- nextjs with custom server

ref:
- https://github.com/vercel/next.js/tree/canary/examples/with-sentry

- https://github.com/getsentry/sentry-javascript/tree/master/packages/nextjs

maybe this is a better place for this issue

https://github.com/rollbar/rollbar.js/issues/979

**Comment by ijsnow** [comment]
Added in the examples directory!
