### ISSUE TITLE
typescript declarations don't work

### ISSUE THREAD

**Issue by luisrudge** [rollbar/rollbar-react#48]
Seems like the index.d.ts file is pointing to a path that is not being published to npm, so running `tsc -b` on a project fails.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/941075/157978356-21c8a4ad-42b6-4670-a9d1-bd1a1c86e09e.png">

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/941075/157978640-597f8c33-4a92-4fc4-8474-57155628374a.png">

**Comment by waltjones** [comment]
@luisrudge Thank you for the report. I'm able to reproduce after turning off `skipLibCheck`. A fix should be ready soon.

**Comment by waltjones** [comment]
Released in v0.11.1.
