### ISSUE TITLE
Invalid hook usage in documentation

### ISSUE THREAD

**Issue by mudetroit** [rollbar/rollbar-react#6]
The README documents the `useRollbarPerson` hook being used in [this manner](https://github.com/rollbar/rollbar-react#userollbarperson-hook)

```
import { useState } from 'react';
import { useRollbarPerson } from '@rollbar/react';
import LoggedInHome  from './LoggedInHome';
import LoggedOutHome from './LoggedOutHome';

function Home() {
  const [currentUser, setCurrentUser] = useState();

  useEffect(async () => {
    const user = await Auth.getCurrentUser();
    if (user) {
      useRollbarPerson(user);
    }
    setCurrentUser(user);
  });

  if (currentUser != null) {
    return <LoggedInHome />;
  }

  return <LoggedOutHome />;
}
```

That usage pattern is flagged by the eslint hook plugin as violating the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html), specifically that the hook is called in a function that is neither a custom hook nor a React component. 

It is also worth noting that it is an improper usage of useEffect in the first place as it is being passed an async function and needs to be given a sync one.

**Comment by eudaimos** [comment]
thanks for adding the issue @mudetroit - updated docs in PR
